### ISSUE TITLE
Extra space char at end of IMAGE_REPO var causes invalid image name resolution

### ISSUE THREAD

**Issue by chrisnorris-da** [digital-asset/cn-quickstart#4]
When doing make start after all other documented steps, I see the docker leg failing with:
```
unable to get image 'digitalasset-canton-network-docker.jfrog.io/digitalasset/ sv-app:0.3.3-snapshot.20241204.7793.0.veab38e18': Error response from daemon: invalid reference format
```

`IMAGE_REPO=digitalasset-canton-network-docker.jfrog.io/digitalasset/ # Publicly released images` includes an extra space at the end before the comment, which I believe is the cause.

**Comment by iggy-da** [comment]
Likely a transient upstream bug in `docker` or similar. There have been no further reports of this across various platforms over the last few months among all users of quickstart, and the `IMAGE_REPO` syntax has remained unchanged. Closing due to being unable to reproduce. Please reopen if still an issue.

**Comment by chrisnorris-da** [comment]
I dont see how it is deemed a transient issue when the logic to generate images in the various compose files is
`    image: "${IMAGE_REPO}canton-participant:${IMAGE_TAG}"
`
and the `IMAGE_REPO` is sent as `digitalasset-canton-network-docker.jfrog.io/digitalasset/ ` (with the extra space).
The fix for this requires just removing the space.

**Comment by iggy-da** [comment]
> I dont see how it is deemed a transient issue

@chrisnorris-da To clarify, I didn't say this is a `transient issue`, but that this looks like `a transient upstream bug in docker or similar`. `docker/make` should remove the whitespace before the comment as per dotfile specs, clearly the white-space before the comment should not become part of the value. In other words this seems to be a bug in your exact version of `docker` or `gnu make`, which was fixed quickly after (upstream in `docker/make`), since this problem has not been observed among any other user of `quickstart`. That you are still experiencing this problem is expected if you are still using the same (apparently broken) version of `docker/make`.

We use the same format with inline-comments all across out `.env` files. [Example section. ](https://github.com/digital-asset/cn-quickstart/blob/8b5416443c2bc3224391b6bd03557e0e559bbaaa/quickstart/.env#L48-L97) I'm not convinced that we should change all that to accommodate buggy tooling localized to one user.

If you would like to investigate further, please provide:
- The version of docker / docker compose you are currently using
- The version of gnu make that you are currently using
- After you have recorded the potentially buggy versions to documented them here for posterity, upgrade docker / gnu make to a more recent version and see if the issue persists.

**Comment by chrisnorris-da** [comment]
`make` is managed by your nix setup so it cannot be relevant as eveyone should be on the same version:
```
❯ which make
/nix/store/ka4fg0rm5hmaji7vwnvzk4qg4dhksg7v-gnumake-4.4.1/bin/make
```
I assume its a docker version issue; where in the docs is the required version specified such that people don't hit this issue?

**Comment by filmackay** [comment]
Docker versions move pretty quickly - we track the latest Docker Desktop version (currently 4.40.0 (187762)). What are you using?

**Comment by filmackay** [comment]
Yes, didn't mean to suggest we should not do what you are describing. We have had many issues in recent years with Docker Desktop on Mac where a change (usually macOS update) breaks something and requires users to use specific Docker Desktop versions (or avoid others).

But I would be very interested whether the problem persists with an update - I am kind of skeptical personally that Docker is to blame, but this would settle that idea!

**Comment by chrisnorris-da** [comment]
Sure, no problem. A docker update has indeed solved it! Do mention it in the setup though (I, for example, could have entirely avoided it if I upgraded first and I'm not massively behind).

**Comment by filmackay** [comment]
Thanks @chrisnorris-da (my skepticism was unfounded!). We do find these upgrades to Docker Desktop have frequently caused problems, and sadly they can't be avoided sometimes with new macOS updates.

**Comment by filmackay** [comment]
@andrae-da are you able to note in the docs that users should be on latest Docker Desktop, at least `4.40.0 (187762)`?
